### ISSUE TITLE
Question on preformance

### ISSUE THREAD

**Issue by xlenstra** [innocentnumbers/dreamwascoded#1]
Why is the entire GUI recreated every 0.5 seconds? Would it not increase performance if only the label text and the graph were recreated?

**Comment by innocentnumbers** [comment]
Not sure where you are seeing that, because the function which updates the GUI is defined as refresh, and has the exact functionality you are describing (See line 255+)! Let me know if there is something I missed however.

**Comment by xlenstra** [comment]
You are correct, I though the while loop in the display function was the main loop in your program, as I missed the call to the tkinter mainloop after creating the GUI. Seeing as that is not the case, I'll close this question.
